### ISSUE TITLE
Exceptions with help on command groups

### ISSUE THREAD

**Issue by nkukard** [stroupbslayen/discord-pretty-help#25]
It seems when using command groups more than 1 level deep I'm getting an error. Perhaps I'm doing something wrong?

The command I am trying to run is this...
```
prefix!help campaign show
```

Here is a snippet of my code...
```
    @commands.group()
    async def campaign(self, ctx: Context) -> None:
        """
        line 1
        line 2
        line 3
        """
        if ctx.author.bot:
            return
        if ctx.invoked_subcommand is None:
            await ctx.send('Invalid sub 1 command passed...')

    @campaign.group()
    async def show(self, ctx: Context) -> None:
        """
        line 1
        line 2
        line 3

        """
        if ctx.author.bot:
            return
        await ctx.send("Campaign list")

    @campaign.group()
    async def create(self, ctx: Context, *args: str) -> None:
        """
        line 1
        line 2
        line 3
        """
        if ctx.author.bot:
            return
```

Here is the exception being raised...
```
bot_1         | Ignoring exception in command help:
bot_1         | Traceback (most recent call last):
bot_1         |   File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
bot_1         |     ret = await coro(*args, **kwargs)
bot_1         |   File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/help.py", line 868, in command_callback
bot_1         |     return await self.send_group_help(cmd)
bot_1         |   File "/usr/local/lib/python3.9/site-packages/pretty_help/pretty_help.py", line 405, in send_group_help
bot_1         |     await self.send_pages()
bot_1         |   File "/usr/local/lib/python3.9/site-packages/pretty_help/pretty_help.py", line 297, in send_pages
bot_1         |     message: discord.Message = await destination.send(embed=pages[0])
bot_1         | IndexError: list index out of range
```

**Comment by stroupbslayen** [comment]
Hey, thanks for pointing this out. I looked into it and it was actually related to groups with 0 commands attached to them and not how deep the group commands are. 

In your example you have created 3 groups of commands (`campaign`, `campaign show`, `campaign create`) but only one of them actually has commands, `campaign`. The way the group help command worked is it required at least one command to iterate through, since there were no commands, there was no list of commands and no embed was created. 

This has been fixed in the newest version. Thanks again for pointing this out!
