### ISSUE TITLE
Doesn't work, error when call

### ISSUE THREAD

**Issue by Mara-Li** [stroupbslayen/discord-pretty-help#27]
Hello ! I saw this and I think it's a great help... But when I invoke my help, using default parameters, I have this : 

```python
Traceback (most recent call last):
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped 
    ret = await coro(*args, **kwargs)
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\help.py", line 836, in command_callback
    return await self.send_bot_help(mapping)
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\pretty_help\pretty_help.py", line 388, in send_bot_help
    self.paginator.add_cog(cog, command_list)
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\pretty_help\pretty_help.py", line 105, in add_cog  
    self._add_command_fields(embed, page_title, commands_list)
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\pretty_help\pretty_help.py", line 119, in _add_command_fields
    if not self._check_embed(
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\pretty_help\pretty_help.py", line 61, in _check_embed
    len(embed) + sum(len(char) for char in chars if char) < self.char_limit
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\embeds.py", line 179, in __len__
    total = len(self.title) + len(self.description)
TypeError: object of type 'Command' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke  
    await ctx.command.invoke(ctx)
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke 
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Lili\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped 
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object of type 'Command' has no len()  
```

Did I miss something ? Could you help me ? Thanks !

**Comment by Mara-Li** [comment]
Okay I found where is the problem : I was a function called "description", and it seems to create a sort of bug between a another command "description", or maybe the embed.

**Comment by stroupbslayen** [comment]
Can you please provide the code you think is causing the issue? Looking at the traceback it looks like somehow a Command is being set as the embeds title or description.

**Comment by Mara-Li** [comment]
No worry, it was my function called description who create a problem ! You can close this issue ^^

**Comment by stroupbslayen** [comment]
Got it, thank you.
