### ISSUE TITLE
NameError: name 'app_commands' is not defined

### ISSUE THREAD

**Issue by tjf1dev** [stroupbslayen/discord-pretty-help#96]
i just installed it and got this

```
Traceback (most recent call last):
  File "c:\Discord\xyz.ai\main\main.py", line 3, in <module>
    from pretty_help import DefaultMenu, PrettyHelp
  File "C:\Users\fajny\AppData\Local\Programs\Python\Python311\Lib\site-packages\pretty_help\__init__.py", line 2, in <module>
    from .pretty_help import *
  File "C:\Users\fajny\AppData\Local\Programs\Python\Python311\Lib\site-packages\pretty_help\pretty_help.py", line 14, in <module>
    class Paginator:
  File "C:\Users\fajny\AppData\Local\Programs\Python\Python311\Lib\site-packages\pretty_help\pretty_help.py", line 122, in Paginator
    command_list: List[Union[commands.Command, app_commands.commands.Command]],
                                               ^^^^^^^^^^^^
NameError: name 'app_commands' is not defined
```

**Comment by CasuallyCalm** [comment]
Looks like discord.py is not installed.

**Comment by rishicorp1** [comment]
MINE IS PY-CORD

**Comment by CasuallyCalm** [comment]
use discord.py
